language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"

notifications:
  email: false

sudo: false

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
